# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', verbose_name='message')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='day')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(default='', verbose_name='header')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('is_free', models.BooleanField(default=True, verbose_name='is_free')),
                ('rating', models.IntegerField(default=0, verbose_name='rating')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.Day')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('username', models.TextField(default='', verbose_name='username')),
                ('first_name', models.TextField(default='', verbose_name='first_name')),
                ('last_name', models.TextField(default='', verbose_name='last_name')),
                ('user_telegram_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=True, verbose_name='vote')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.Event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.TelegramUser')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.TelegramUser'),
        ),
    ]
