# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_auto_20170421_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='week_day_id',
            field=models.IntegerField(default=-1, verbose_name='week_day_id'),
        ),
    ]
