# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_telegramuser_free_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('message_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('chat_id', models.BigIntegerField(default=-1, verbose_name='chat_id')),
                ('text', models.CharField(default=True, max_length=999, verbose_name='text')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.Event')),
            ],
        ),
    ]
