# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_botmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='text')),
            ],
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_VIP',
            field=models.BooleanField(default=False, verbose_name='is_VIP'),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='text',
            field=models.TextField(default='', verbose_name='text'),
        ),
    ]
