# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0006_auto_20170425_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.CharField(default='', max_length=999, verbose_name='text')),
            ],
        ),
    ]
