# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0007_eventhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventHistory',
        ),
    ]
